' Copyright (c) 2017,  Met Office, on behalf of HMSO and Queen's Printer
' For further details please refer to the file LICENCE.original which you
' should have received as part of this distribution.

class scalar_mod::scalar_type {
  +value : real

  <<create>>+scalar_constructor( <<in>>value:real ) : scalar_type

  +get_sum() : real
  +get_min() : real
  +get_max() : real
  +reduction_finish()
}
