' (c) Crown copyright 2021 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

@startuml

!include look.iuml
!include utilities/event_mod.iuml
!include io/io_context_mod.iuml

io_context_mod::io_context_type ^- event_mod::event_actor_type

@enduml