' (C) Crown copyright 2017 Met Office. All rights reserved.
' For further details please refer to the file LICENCE which you should have
' received as part of this distribution.

abstract class abstract_quadrature_mod::abstract_quadrature_type {
}
