#!/bin/sh
##############################################################################
# Copyright (c) 2017,  Met Office, on behalf of HMSO and Queen's Printer
# For further details please refer to the file LICENCE.original which you
# should have received as part of this distribution.
##############################################################################
#
# Wrap the submission of a job into something which can be called from a
# build system. You are limited to one nodes worth of processors and 1 minute
# wallclock.
#
# Usage:
#   run_cray <compiler> <processes> <executable>
#

COMPILER=$1
PROCESSES=$2
EXECUTABLE=$3

BATCH_SCRIPT=$(mktemp --tmpdir=$HOME --suffix=".pbs")

cat >$BATCH_SCRIPT <<EOT
#!/bin/sh
##############################################################################
# Copyright (c) 2017,  Met Office, on behalf of HMSO and Queen's Printer
# For further details please refer to the file LICENCE.original which you
# should have received as part of this distribution.
##############################################################################
#
# Define a name for the job
#PBS -N dynamo
# Select the queue to run on
#PBS -q shared
# Select the number of nodes on which to run
#PBS -l select=1
# Select the length of time for which you want to run the job hh:mm:ss
#PBS -l walltime=00:01:00

#
# Submission script for submitting a Dynamo job to machines that use the
# Portable Batch System (PBS). For example Archer or the Met Office Cray systems
#
set -x
echo Set working directory
export PBS_O_WORKDIR=\$(readlink -f \$PBS_O_WORKDIR)
cd \$PBS_O_WORKDIR

echo Load modules
. /data/d04/mhambley/modules/setup
module load meto-environment/dynamo/compiler/$COMPILER
module load cray-snplauncher
module list

echo Run program
mpiexec -n $PROCESSES ./$EXECUTABLE
EOT

qsub -Wblock=true $BATCH_SCRIPT
RC=$?
echo $RC
rm $BATCH_SCRIPT

exit $RC

