#!/bin/sh
##############################################################################
# Copyright (c) 2017,  Met Office, on behalf of HMSO and Queen's Printer
# For further details please refer to the file LICENCE.original which you
# should have received as part of this distribution.
##############################################################################
#
# Prepare a stand-alone environment for building Dynamo
#

# BESPOKE_HDF5_WATCHDOG_TIME=10800

LOGFILE=$PWD/dynamoprep.log
echo `date` >$LOGFILE

TERMINAL=`tty`
echo Starting... > $TERMINAL

BITNESS=`file -L /sbin/init | cut -d " " -f 3 | cut -d "-" -f 1`

WORKDIR=$HOME/local/src
INSTALLDIR=$HOME/local/dynamo

###############################################################################
# Trap failure
#
trap 'echo "Failed"; trap - EXIT; exit 1' EXIT

###############################################################################
# Check for DEB packages.
# Arguments:
#   (absent|present) Report packages which are missing or not
#
check_apt_packages() {
  interest=$1
  shift
  echo Checking packages $@ | tee -a $LOGFILE > $TERMINAL
  found=""
  notfound=""
  for package in $@; do
    dpkg -s $package 2>>$LOGFILE 1>>$LOGFILE \
        && found="$found $package" || notfound="$notfound $package"
  done

  if [ $interest = 'present' ] ; then
    echo $found
  else
    echo $notfound
  fi
}

###############################################################################
# Chek for RPM packages.
# Arguments:
#   (absent|present) Report packages which are missing or not
#
check_rpm_packages() {
  echo Checking packages $@ | tee -a $LOGFILE > $TERMINAL
  interest=$1
  shift
  found=""
  notfound=""
  for package in $@; do
    rpm -q $package 2>>$LOGFILE 1>>$LOGFILE \
        && found="$found $package" || notfound="$notfound $package"
  done

  if [ $interest = 'present' ] ; then
    echo $found
  else
    echo $notfound
  fi
}

###############################################################################
# A quick function to download and extract a tarball
# Arguments:
#   Tarball URL
# Return:
#   The extracted directory
#
download_extract() {
  leafname=`basename $1`
  mkdir -p $WORKDIR
  if [ ! -r $WORKDIR/$leafname ] ; then
    echo Getting tarball: $1 | tee -a $LOGFILE > $TERMINAL
    wget -P $WORKDIR $1 || return 1
  fi

  extract_dir=`tar -tf $WORKDIR/$leafname | head -n 1 | cut -d / -f 1`
  if [ ! -d $WORKDIR/$extract_dir ] ; then
    echo Extracting tarball $WORKDIR/$extract_dir | tee -a $LOGFILE > $TERMINAL
    tar -C $WORKDIR -xf $WORKDIR/$leafname || return 1
  fi

  echo $WORKDIR/$extract_dir
}

###############################################################################
# Run an auto-conf script to prepare for an out-of-directory build
# Arguments:
#   Source directory
#   Additional arguments for configuration
# Returns:
#   Build directory
#
configure() {
  build_dir=$1-build
  if [ ! -d $build_dir ] ; then
    echo Configuring build: $1 | tee -a $LOGFILE > $TERMINAL
    mkdir -p $build_dir
    cd $build_dir
    $1/configure --prefix=$INSTALLDIR $2 2>>$LOGFILE 1>>$LOGFILE || return 1
  fi

  echo $build_dir
}

###############################################################################
# Compile and install
# Arguments:
#   Build directory
#
compile_install() {
  echo Compiling: $1 | tee -a $LOGFILE > $TERMINAL
  cd $1
  make -j 2 2>>$LOGFILE 1>>$LOGFILE || return 1
  make check install 2>>$LOGFILE 1>>$LOGFILE || return 1
}

###############################################################################
# Main program
#
which dpkg 2>/dev/null 1>/dev/null && dpkg_found=1
which rpm 2>/dev/null 1>/dev/null && rpm_found=1

if [ $dpkg_found ] ; then
  like_packages=$(check_apt_packages 'absent' subversion wget \
                                     gfortran-4.9 g++-4.9 m4 make file patch \
                                     libtool cmake doxygen zlib1g-dev \
                                     openjdk-7-jre xsltproc)
  hate_packages=$(check_apt_packages 'present' libnetcdff5 )

  export FC=gfortran-4.9
  export CXX=g++-4.9
  export CC=gcc-4.9
  export CPP=cpp-4.9
  export FPP="cpp-4.9 -traditional-cpp"
elif [ $rpm_found ] ; then
  like_packages=$(check_rpm_packages 'absent' subversion wget \
                                              gcc-gfortran-4.8.2 gcc-c++-4.8.2 \
                                              m4 make file patch libtool cmake \
                                              doxygen zlib-devel)
  hate_packages=$(check_rpm_packages 'present' )

  export FC=gfortran
  export CXX=g++
  export CC=gcc
  export CPP=cpp
  export FPP="cpp -traditional-cpp"
else
  echo "Can't identify the package manager"
  exit 1
fi

if [ "x$like_packages" != "x" ] ; then
  echo Please install the following packages: $like_packages
  exit 1
fi

if [ "x$hate_packages" != "x" ] ; then
  echo Cannot build with the following packages installed: $hate_packages
  exit 1
fi

export PATH=$INSTALLDIR/bin:$PATH
export CPPFLAGS="-I$INSTALLDIR/include -I/usr/include"
export FFLAGS="-I$INSTALLDIR/mod/modO/Linux.gfortran.$BITNESS.mpiuni.default"
export LDFLAGS="-L$INSTALLDIR/lib -L$INSTALLDIR/lib/libO/Linux.gfortran.$BITNESS.mpiuni.default -L/usr/lib"
export LD_LIBRARY_PATH=$INSTALLDIR/lib:$INSTALLDIR/lib/libO/Linux.gfortran.$BITNESS.mpiuni.default:$LD_LIBRARY_PATH

grep "Ubuntu" /etc/os-release 1>>$LOGFILE && export LDFLAGS="$LDFLAGS -Wl,--no-as-needed"

# Compile and install an MPI library
#
if [ ! -e $INSTALLDIR/lib/libmpich.so ] ; then
  echo Installing MPICH
  source_dir=$(download_extract 'http://www.mpich.org/static/downloads/3.1.4/mpich-3.1.4.tar.gz' ) || exit 1
  build_dir=$(configure $source_dir) || exit 1
  $(compile_install $build_dir) || exit 1
else
  export MPILD=mpif90
fi

# Compile and install the HDF5 library
#
if [ ! -e $INSTALLDIR/lib/libhdf5.so ] ; then
  (
    echo Installing HDF5
    FC=mpif90
    CC=mpicc
    CXX=mpic++
    HDF5_PARAPREFIX=/var/tmp/hdf5-test
    # Slow machines may suffer time-outs during the testing of HDF5
    if [ "x$BESPOKE_HDF5_WATCHDOG_TIME" != "x" ] ; then
      export HDF5_ALARM_SECONDS=$BESPOKE_HDF5_WATCHDOG_TIME
      echo Setting HDF5 testing time limit to $HDF5_ALARM_SECONDS seconds
    fi
    source_dir=$(download_extract 'http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.14.tar.gz' ) || exit 1
    build_dir=$(configure $source_dir "--enable-parallel --enable-shared --enable-fortran --enable-fortran2003 --enable-cxx --enable-unsupported") || exit 1
    # HDF5 has a dodgy libtool script which it uses in preference to the system
    # version
    rm $build_dir/libtool
    cp `which libtool` $build_dir
    $(compile_install $build_dir) || exit 1
    rm -rf $HDF5_PARAPREFIX
  ) || exit 1
fi

# Compile and install NetCDF library
#
if [ ! -e $INSTALLDIR/lib/libnetcdf.so ] ; then
  echo Installing NetCDF
  source_dir=$(download_extract 'ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.3.3.1.tar.gz' ) || exit 1
  build_dir=$(configure $source_dir) || exit 1
  $(compile_install $build_dir) || exit 1
fi

if [ ! -e $INSTALLDIR/lib/libnetcdff.so ] ; then
  echo Installing NetCDF-Fortran
  source_dir=$(download_extract 'ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-fortran-4.4.2.tar.gz' ) || exit 1
  build_dir=$(configure $source_dir) || exit 1
  $(compile_install $build_dir) || exit 1
fi
 if [ ! -e $INSTALLDIR/lib/libnetcdf_c++.so ] ; then
  echo Installing NetCDF-C++ Legacy
  source_dir=$(download_extract 'ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-cxx-4.2.tar.gz' ) || exit 1
  build_dir=$(configure $source_dir) || exit 1
  $(compile_install $build_dir) || exit 1
fi

# Compile and install the ESMF library
#
if [ ! -e $INSTALLDIR/lib/libO/Linux.gfortran.$BITNESS.mpiuni.default/libesmf.so ] ; then
  echo Installing ESMF
  mkdir -p $WORKDIR
  if [ ! -r $WORKDIR/esmf_6_3_0rp1_src.tar.gz ] ; then
    echo Getting tarball
    wget -P $WORKDIR http://www.earthsystemmodeling.org/esmf_releases/non_public/ESMF_7_0_0/esmf_7_0_0_src.tar.gz
  fi

  if [ ! -d $WORKDIR/esmf ] ; then
    echo Extracting tarball
    tar -C $WORKDIR -xf $WORKDIR/esmf_6_3_0rp1_src.tar.gz
    echo Patching sources
    patch -d $WORKDIR/esmf/build_config/Linux.gfortran.default <<EOP
--- build_rules.mk.orig	2015-03-05 19:39:54.816919176 +0000
+++ build_rules.mk	2015-03-05 19:40:15.559276033 +0000
@@ -6,8 +6,9 @@
 ############################################################
 # Default compiler setting.
 #
-ESMF_F90DEFAULT         = gfortran
-ESMF_CXXDEFAULT         = g++
+ESMF_F90DEFAULT         = gfortran-4.9
+ESMF_CXXDEFAULT         = g++-4.9
+ESMF_CPPDEFAULT         = gcc-4.9 -E -P -x c
 
 ############################################################
 # Default MPI setting.
EOP
  fi

  echo Building ESMF | tee -a $LOGFILE
  env ESMF_DIR=$WORKDIR/esmf \
      ESMF_INSTALL_PREFIX=$INSTALLDIR \
      ESMF_COMPILER=gfortran \
      ESMF_COMMS=mpich2 \
      ESMF_NETCDF=split \
      ESMF_NETCDF_INCLUDE_DIR=$INSTALLDIR/include \
      ESMF_NETCDF_LIBPATH=$INSTALLDIR/lib \
      make -C $WORKDIR/esmf 2>>$LOGFILE 1>>$LOGFILE || exit 1
  echo Testing ESMF | tee -a $LOGFILE
  env ESMF_DIR=$WORKDIR/esmf \
      ESMF_INSTALL_PREFIX=$INSTALLDIR \
      ESMF_COMPILER=gfortran \
      ESMF_COMMS=mpich2 \
      ESMF_NETCDF=split \
      ESMF_NETCDF_INCLUDE_DIR=$INSTALLDIR/include \
      ESMF_NETCDF_LIBPATH=$INSTALLDIR/lib \
      make -C $WORKDIR/esmf check install 2>>$LOGFILE 1>>$LOGFILE || exit 1
fi

echo Done

# Release exit trap to avoid reporting error on a normal exit.
#
trap - EXIT
