#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
##############################################################################
# Copyright (c) 2017,  Met Office, on behalf of HMSO and Queen's Printer
# For further details please refer to the file LICENCE.original which you
# should have received as part of this distribution.
##############################################################################
'''!
Timestamp a file with the last update time of a Subversion repository.

The file will contain the associated revision number.
'''

from __future__ import print_function

import argparse
import os
import doctools.subversive

def version():
    '''!
    This application's version number.

    @return (str) The version number.
    '''
    return '1.0'

def tagToRevision( repoURL, tag ):
    '''!
    Converts a release version tag to a corresponding trunk revision.
    
    @param repoURL (str) URL of the repository.
    @param tag (str) Tag within repository.
    
    @return (tuple) Trunk revision number of the tag and timestamp of cut.
    '''
    if tag:
        return doctools.subversive.subversionTagOrigin( repoURL, tag )
    else:
        return None

def headaliser(repoURL, firstRevision, lastRevision, outputName):
    '''!
    Force a file to have the same modification timestamp as a repository.

    @param repoURL (str) The URL of the repository.
    @param firstRevision (tuple) Revision and timestamp or None.
    @param lastRevision (tuple) Revision and timestamp or None.
    @param outputName (str) The file to received the revision number of "head"
                      and be time stamped.
    '''
    info = doctools.subversive.subversionInfo(repoURL)

    if not lastRevision:
        lastRevision = (info['latest-revision'], info['latest-revision-time'])

    with open(outputName, 'w') as output:
        if firstRevision:
            print( str(firstRevision[0]), end='', file=output )
        else:
            print( '0', end='', file=output )
        print( ':' + str(lastRevision[0]), file=output )

    current = os.stat(outputName)
    os.utime( outputName, ( current.st_atime, lastRevision[1] ) )

if __name__ == '__main__':
    parser = argparse.ArgumentParser(add_help = False, \
             description='Stamp a file with the timestamp of the last repository update.')
    parser.add_argument('-help', '-h', '--help', action='help', \
                        help='Display this help message.')
    parser.add_argument('-version', action='version', \
                        version='%(prog)s {}'.format(version()), \
                        help='Display version information.')
    parser.add_argument('-release', metavar='tag:tag', \
                        help='Releases to obtain revisions for.')
    parser.add_argument('repositoryURL', metavar='URL', \
                        help='The repository URL.')
    parser.add_argument('outputFilename', metavar='filename', \
                        help='The repository timestamp file to write.')
    args = parser.parse_args()

    upperRevision = None
    lowerVersion  = None
    if args.release:
        bracketVersions = list(args.release.split( ':', 2 ))
        upperVersion = bracketVersions.pop(-1)
        if bracketVersions:
            lowerVersion = bracketVersions.pop(-1)

    if lowerVersion == 'ROOT':
      lowerRevision = None
    else:
      lowerRevision = tagToRevision( args.repositoryURL, lowerVersion )

    if upperVersion == 'HEAD':
      upperRevision = None
    else:
      upperRevision = tagToRevision( args.repositoryURL, upperVersion )

    headaliser( args.repositoryURL, lowerRevision, upperRevision, \
                args.outputFilename )

