' (c) Crown copyright 2020 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

@startuml

!include look.iuml
!include lfric_xios_context_mod.iuml
!include lfric_xios_file_mod.iuml
!include lfric_xios_field_mod.iuml
!include lfric_xios_time_axis_mod.iuml

lfric_xios_context_type -> lfric_xios_file_type
lfric_xios_file_type -> lfric_xios_field_type
lfric_xios_file_type -> lfric_xios_time_axis_mod::time_axis_type
@enduml
