' (C) Crown copyright 2022 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

class id_r32_field_array_pair_mod::id_r32_field_array_pair_type {
  -field_array_: field_real32_type

  +initialise( <<in>> fs: function_space_type, <<in>> id: integer, <<in>> array_size: integer )
  +copy_initialise( <<in>> field_array: field_real32_type, <<in>> id: integer ) :
  +get_field_array( ) : field_real32_type
  <<destroy>>+destructor()
}
