' (C) Crown copyright 2022 Met Office. All rights reserved.
' The file LICENCE, distributed with this code, contains details of the terms
' under which the code may be used.

class id_r32_operator_pair_mod::id_r32_operator_pair_type {
  -operator_: operator_real32_type

  +initialise( <<in>> fs_target: function_space_type, <<in>> fs_source: function_space_type, <<in>> id: integer )
  +copy_initialise( <<in>> operator_in: operator_real32_type, <<in>> id: integer ) :
  +get_operator( ) : operator_real32_type
  <<destroy>>+destructor()
}
