#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
##############################################################################
# (c) The copyright relating to this work is owned jointly by the Crown,
# Met Office and NERC 2014. However, it has been created with the help of the
# GungHo Consortium, whose members are identified at
# https://puma.nerc.ac.uk/trac/GungHo/wiki
##############################################################################
'''
Generate a make file snippet holding build information about a Fortran
program.

This snippet consists of alist of objects required to link an program.

This snippet may then be "include"ed into other make files.
'''

from __future__ import print_function;

import argparse
import os

from dependencyanalysis import __version__
import dependencyanalysis.database as database
import dependencyanalysis.logging  as logging
import dependencyanalysis.process  as process

###############################################################################
# Entry point

if __name__ == '__main__':
    parser = argparse.ArgumentParser( add_help=False, \
                                      description=__doc__ )
    parser.add_argument( '-help', '-h', '--help', action='help', \
                         help='Show this help message and exit' )
    parser.add_argument( '-version', action='version', \
                         version='%(prog)s {}'.format( __version__ ) )
    parser.add_argument( '-verbose', action='store_true', \
                         help='Provide a running commentry' )
    parser.add_argument( '-database', metavar='database-file', \
                         help='Database file to use' )
    parser.add_argument( '-objectdir', metavar='object-directory', \
                         help='Object files are here. ' \
                              + 'Defaults to the output directory.' )
    parser.add_argument( 'output', metavar='output-file', \
                         help='Dependency details are put here' )
    args = parser.parse_args()

    if args.verbose:
        logger = logging.PrintLogger( sys.stdout )
    else:
        logger = logging.NoLogger()

    if os.path.exists( args.output ):
        os.unlink( args.output )

    outputDirectory = os.path.dirname( args.output )
    if not os.path.exists( outputDirectory ):
        os.makedirs( outputDirectory )

    if not args.database: args.database = os.path.join( outputDirectory, \
                                                        dependencies.db )
    if not args.objectdir: args.objectdir = outputDirectory

    dependencyStore = database.Dependencies( args.database )
    processor = process.Processor( logger, dependencyStore, \
                                   args.objectdir, None )

    try:
        with open( args.output, 'w' ) as listFile:
            processor.programObjects( listFile )
    except:
        os.path.unlink( ars.output )
